security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    firewalls:
        wsse_secured:
            pattern:   ^/api/.*
            #todo insert env variable
            wsse:      { nonce_dir: "%kernel.root_dir%/cache/wsse/", lifetime: 300 }
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: /api/register/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /api/.*, roles: ROLE_USER }
        - { path: /application/show/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /application/.*/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /application/.*, roles: ROLE_USER }
        - { path: /page/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    factories:
        - "%kernel.root_dir%/../vendor/bundles/Escape/WSSEAuthenticationBundle/Resources/config/security_factories.yml"
    acl:
        connection: default
