jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /
                use_referer: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: /api/register/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /api/.*, roles: ROLE_USER }
        - { path: /application/show/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /application/.*/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /application/.*, roles: ROLE_USER }
        - { path: /payment/interkassa/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /payment/.*, roles: ROLE_USER }
        - { path: /page/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    #factories:
    #    - "%kernel.root_dir%/../vendor/bundles/Escape/WSSEAuthenticationBundle/Resources/config/security_factories.yml"
    acl:
        connection: default
