DefaultBundle_homepage:
  pattern:  /
  defaults: { _controller: DefaultBundle:Default:index }
DefaultBundle_static_page:
  pattern:  page/{slug}
  defaults: { _controller: DefaultBundle:Page:index }
  requirements:
    slug:  about|contacts|reglament-stay-alive-2013|information-stay-alive-2013|faq-stay-alive-2013
DefaultBundle_payment_response:
  pattern:  payment/{slug}
  defaults: { _controller: DefaultBundle:Page:index }
  requirements:
    slug:  success|fail
