parameters:
#    sar_sport_user.example.class: SarSport\Bundle\UserBundle\Example

services:
#    sar_sport_user.example:
#        class: %sar_sport_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_user.registration.form.type:
        class: SarSport\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sarsport_user_registration }
